{% set name = "doxygen" %}
{% set version = "1.8.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.src.tar.gz  # [not win]
  url: http://doxygen.nl/files/{{ name }}-{{ version }}.src.tar.gz  # [not win]
  sha256: 673bd87fa5595480a7abe6828c8cd5f17e3d330023f647dde07b92ee7f437960  # [not win]

  fn: {{ name }}-{{ version }}.windows.x64.bin.zip  # [win]
  url: http://doxygen.nl/files/{{ name }}-{{ version }}.windows.x64.bin.zip  # [win]
  sha256: d83bf91ce448e4f935ce0a834360da7d767ef1805afef16d624ce9a86aa6f211  # [win]

  patches:   # [not win]
    # CMake finds iconv_open in glibc, but finds iconv.h from libiconv.
    # Make sure both are found from one place.
    - find_iconv.patch                                                           # [not win]

build:
  number: 0
  script:   # [win]
    - mkdir %SCRIPTS%                                      # [win]
    - copy doxygen.exe %SCRIPTS%\ || goto :eof             # [win]
    - copy doxyindexer.exe %SCRIPTS%\ || goto :eof         # [win]
    - copy doxysearch.cgi.exe %SCRIPTS%\ || goto :eof      # [win]
    - copy libclang.dll %LIBRARY_BIN%\ || goto :eof        # [win]
    - copy libclang.dll %LIBRARY_BIN%\ || goto :eof        # [win]
    - copy %RECIPE_DIR%\LICENSE %SRC_DIR%\ || goto :eof    # [win]

requirements:   # [not win]
  build:   # [not win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - bison         # [not win]
    - cmake         # [not win]
    - make          # [not win]
    - flex          # [not win]
    - m4            # [not win]
    - python        # [not win]
    - texlive-core  # [not win]
  host:   # [not win]
    - libiconv      # [not win]
  run:   # [not win]
    - libiconv      # [not win]

test:
  commands:
    - doxygen --help

about:
  home: http://www.stack.nl/~dimitri/doxygen/index.html
  license: GPL2
  license_file: LICENSE
  summary: Generate documentation from source code

  description: |
    Doxygen is the de facto standard tool for
    generating documentation from annotated C++ sources,
    but it also supports other popular programming
    languages such as C, Objective-C, C#, PHP, Java,
    Python, IDL (Corba, Microsoft, and UNO/OpenOffice flavors),
    Fortran, VHDL, Tcl, and to some extent D.
  doc_url: http://www.stack.nl/~dimitri/doxygen/manual/index.html
  dev_url: https://github.com/doxygen/doxygen

extra:
  recipe-maintainers:
    - bluescarni
    - isuruf
    - tadeu
