{% set name = "doxygen" %}
{% set version = "1.8.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.src.tar.gz                                                  # [not win]
  url: ftp://ftp.stack.nl/pub/users/dimitri/{{ name }}-{{ version }}.src.tar.gz            # [not win]
  sha256: d1757e02755ef6f56fd45f1f4398598b920381948d6fcfa58f5ca6aa56f59d4d                 # [not win]

  fn: {{ name }}-{{ version }}.windows.bin.zip                                             # [win32]
  url: http://ftp.stack.nl/pub/users/dimitri/{{ name }}-{{ version }}.windows.bin.zip      # [win32]
  sha256: c88e2ff9b5a27a255e8d4c655cd63f5a6c3786e016ce7c88fc585cc58f2c8704                 # [win32]

  fn: {{ name }}-{{ version }}.windows.x64.bin.zip                                         # [win64]
  url: http://ftp.stack.nl/pub/users/dimitri/{{ name }}-{{ version }}.windows.x64.bin.zip  # [win64]
  sha256: 742f77a3a55ae438076958e7103e95864fd8ed62ee86ce203e092a6792618f9c                 # [win64]

  patches:                                                                       # [not win]
    # CMake finds iconv_open in glibc, but finds iconv.h from libiconv.
    # Make sure both are found from one place.
    - find_iconv.patch                                                           # [not win]

build:
  number: 1
  skip: True  # [not py35 and unix]
  script:                                                  # [win]
      - mkdir %SCRIPTS%                                    # [win]
      - copy doxygen.exe %SCRIPTS%\ || goto :eof           # [win]
      - copy doxyindexer.exe %SCRIPTS%\ || goto :eof       # [win]
      - copy doxysearch.cgi.exe %SCRIPTS%\ || goto :eof    # [win]
      - copy libclang.dll %LIBRARY_BIN%\ || goto :eof      # [win]
      - copy libclang.dll %LIBRARY_BIN%\ || goto :eof      # [win]
      - copy %RECIPE_DIR%\LICENSE %SRC_DIR%\ || goto :eof  # [win]

requirements:       # [not win]
  build:
    - cmake         # [not win]
    - texlive-core  # [not win]
    - m4            # [not win]
    - {{ compiler('c') }}
  host:            # [not win]
    - flex          # [not win]
    - bison         # [not win]
    - python        # [not win]
    - libiconv      # [not win]
  run:              # [not win]
    - libiconv      # [not win]

test:
  commands:
    - doxygen --help

about:
  home: http://www.stack.nl/~dimitri/doxygen/index.html
  license: GPL2
  license_file: LICENSE
  summary: 'Generate documentation from source code'

  description: |
    Doxygen is the de facto standard tool for
    generating documentation from annotated C++ sources,
    but it also supports other popular programming
    languages such as C, Objective-C, C#, PHP, Java,
    Python, IDL (Corba, Microsoft, and UNO/OpenOffice flavors),
    Fortran, VHDL, Tcl, and to some extent D.
  doc_url: http://www.stack.nl/~dimitri/doxygen/manual/index.html
  dev_url: https://github.com/doxygen/doxygen

extra:
  recipe-maintainers:
    - bluescarni
    - isuruf
    - tadeu
