{% set name = "doxygen" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.src.tar.gz
  url: http://doxygen.nl/files/{{ name }}-{{ version }}.src.tar.gz
  sha256: da8a393b7f8b7442653475a0a4bc6eaa9ce60623440d14a82fef4e8d99da4b85

  patches:
    # CMake finds iconv_open in glibc, but finds iconv.h from libiconv.
    # Make sure both are found from one place.
    - find_iconv.patch

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bison  # [not win]
    - cmake
    - flex  # [not win]
    - m4  # [not win]
    - make  # [not win]
    - miktex  # [win]
    - ninja  # [win]
    - python
    - texlive-core  # [not win]
    - winflexbison  # [win]
  host:
    - libiconv
  run:
    - libiconv

test:
  commands:
    - doxygen --help

about:
  home: http://www.stack.nl/~dimitri/doxygen/index.html
  license: GPL2
  license_file: LICENSE
  summary: Generate documentation from source code

  description: |
    Doxygen is the de facto standard tool for
    generating documentation from annotated C++ sources,
    but it also supports other popular programming
    languages such as C, Objective-C, C#, PHP, Java,
    Python, IDL (Corba, Microsoft, and UNO/OpenOffice flavors),
    Fortran, VHDL, Tcl, and to some extent D.
  doc_url: http://www.stack.nl/~dimitri/doxygen/manual/index.html
  dev_url: https://github.com/doxygen/doxygen

extra:
  recipe-maintainers:
    - bluescarni
    - isuruf
    - tadeu
