# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ntIOsNMesm5eSWM9WAj3Q4fbRYFGtiYz/yOav03Oml3ltCxOS2sqh1fyhtvjZL1q+LlMyVMqi+8EVQ4RQBT3JjwgP7BWCnS/h6B3mS8UEXcmAx3528LI0hS5S1LvnsTzWJjFeKJrs6E6Xv1zWVOH/1NhrAD6VXRYgHvKZadW6h8ObfXWUmY9XGkWrQQEeJh/bFT/27+T6GvqM2xB/h+B6QaMG7HSpPe+erTcKIRgBc392T82jpoWP1UC5AaO9PikqrfYbYTQDx9XfBKTj/LJNwq0rNo7HPhv7tTbdPdKAJpIHCfXR2iZ6uNeo/sWsgmalc0eZqC6QOQOeoNtUBbxpfsy23pypMo6QOjBmV6UsV1J9cTRdLjE0Ex2VGOpnY0msoCsFjLHwz8bnFRWJQNkBvOlFFJygHv6jAOrHBjJ3Ki+apYyvTBlVER1zU1RsS0uMeKl2/c4979STkDIzbuSrA6h0o8x4Ivy6kUYR8AvYDupI9AomTDQv1ZMwl2xLPIZS0U9lEV9apAMeWWk2V5XkNUlqWzZ46NnP9zzA32mPnkbc02Ceuuwwc0eeLRvXdGPCoBfTUJ+aV5Cn6BDCljgpG2u4rRF96QuzHB5sE3oR/DhAyxEBwINBQQedBSuYsOnic9P1yiCLyly/iza6Q4tXrrY0MoUQc6kgczLul8KoIc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
